.github/workflows/release-please.yaml

chore: Update release-please.yaml

---

.tests/jenkins/config.yaml

test: update jenkins config file

---

config/multiqc_config_DNA.yaml

Lab wants _N to be removed from multiqc

fix: update multiqc_config_DNA.yaml

---

config/config.yaml
random_stuff

fix: WGS genepanel in config.yaml

---

config/config.yaml
config/config_bianca.yaml
config/resources.yaml
config/resources_bianca.yaml
workflow/Snakefile
workflow/rules/common.smk

feat: support running the pipeline on bianca cluster

---

.tests/integration/config/config.yaml
config/config.yaml
config/config_bianca.yaml
config/resources.yaml
config/resources_bianca.yaml
workflow/Snakefile
workflow/scripts/create_excel.py

feat: handle when the coverage bed file that has mitochondria genes 

---

requirements.txt
start_HG_marvin.sh
workflow/rules/common.smk

fix: handle incomplete trios

---

workflow/Snakefile

fix(Snakefile): add rule order for bgzip and rename rule

---

scripts/extract_samples_info.py

fix: handle col creation when no trios present

---

.readthedocs.yaml

docs: Update .readthedocs.yaml

---

.github/workflows/test-build-mkdocs

test: Update test-build-mkdocs

---

workflow/rules/concat_vcfs.smk

fix: remove remining conda references

---

.readthedocs.yaml

docs: change python version in .readthedocs.yaml

---

README.md

docs: add docs build badge to README.md

---

workflow/rules/common.smk
workflow/rules/extract_str_bed.smk
workflow/scripts/extract_str_bed.py

fix: correctly set the panel path as a string

---

config/multiqc_config_DNA.yaml
workflow/rules/common.smk

fix: used fixed string instead of date for version file

---

.tests/integration/config/config.yaml
.tests/integration/config/config_hard_filter_germline.yaml
.tests/integration/config/output_list.json
config/config.yaml
config/config_bianca.yaml
config/config_hard_filter_germline.yaml
config/output_list.json
config/resources.yaml
workflow/Snakefile
workflow/rules/common.smk
workflow/rules/coverage.smk
workflow/rules/vcf_to_aed.smk
workflow/scripts/create_excel.py

feat: remove tiddit from svdb merge and use --no_intra in merge

---

workflow/Snakefile

fix: add bai as input for tiddit

---

config/multiqc_config_DNA.yaml
workflow/scripts/create_excel.py

feat: generalise how transcript id is extracted

---

config/config.yaml

feat: update parabricks module

---

.github/workflows/release-please.yaml

chore: Update release-please-action to version 3
